### ISSUE TITLE
DigitalOcean droplet no networking

### ISSUE THREAD

**Issue by pguizeline** [GortCodex/DNSCrypt-Loader#10]

**Comment by GortCodex** [comment]
Hello, thanks for using DNSCrypt-loader. 

It seems that just a fine tuning on your settings. 
Make sure your DNS queries point to the correct ports. 
In dnscrypt-loader script default is:
cPrimaryIP = "127.0.0.1"
cPrimaryPort = "5553"
and
cSecondaryIP = "127.0.0.1"
cSecondaryPort = "5554"

The link below gives an idea of how to redirect the DNS traffic using dnscrypt-proxy and dnsmasq. 

https://wiki.debian.org/HowTo/dnsmasq
