### ISSUE TITLE
dnscrypt-proxy v1.9.3 doesn't work with dnscrypt-loader

### ISSUE THREAD

**Issue by jpgpi250** [GortCodex/DNSCrypt-Loader#11]
I've installed / upgraded dnscrypt-proxy, using dnscrypt-loader, using these [instructions](https://discourse.pi-hole.net/t/setting-up-and-using-dnscrypt-loader/606/8). dnscrypt-proxy and dnscrypt-loader do not start anymore.
The syslog messages are:
Jan 19 10:06:06 raspberrypi dnscrypt-loader: The path to resolvers.csv on dnscrypt-loader script
Jan 19 10:06:06 raspberrypi dnscrypt-loader: differs from dnscrypt-proxy setup
Jan 19 10:06:06 raspberrypi dnscrypt-loader: Please change dnscrypt-loader 'cCSVBaseDir' and 'cSIGBaseDir' parameters to
Jan 19 10:06:06 raspberrypi dnscrypt-loader: cCSVBaseDir='/'
Jan 19 10:06:06 raspberrypi dnscrypt-loader: cSIGBaseDir='/'
Jan 19 10:06:06 raspberrypi dnscrypt-loader: Edit script at /usr/local/sbin/dnscrypt-loader
Changing the parameters, as indicated by this message doesn't solve the problem...
the resolver.csv files are in /usr/local/share/dnscrypt-proxy, this path matches the configuration in the (unchanged) dnscrypt-loader configuration file (/usr/local/sbin/dnscrypt-loader)

**Comment by GortCodex** [comment]
Hello jpgpi250 

To try to resolve the problem, 
match the paths defined in the parameters with the path where dnscrypt-proxy and resolvers.csv were saved.

Using whereis and find commands examples:

$ whereis dnscrypt-proxy
dnscrypt-proxy: /usr/local/sbin/dnscrypt-proxy

Set cProxyBaseDir to:
cProxyBaseDir="/usr/local/sbin/"


$ find / -name dnscrypt-resolvers.csv
/usr/local/share/dnscrypt-proxy/dnscrypt-resolvers.csv

Set cCSVBaseDir and cSIGBaseDir to:

cCSVBaseDir="/usr/local/share/dnscrypt-proxy/"
cSIGBaseDir="/usr/local/share/dnscrypt-proxy/"


Thanks for reporting this issue.

**Comment by jpgpi250** [comment]
I've checked the configuration paths, they match

system info 2016-11-25-raspbian-jessie-lite, running on raspberry pi 3 model B

when trying to start dnscrypt-loader, this is the output:
sudo dnscrypt-loader
Thu Jan 19 14:26:46 2017 [ERROR] Error: no resolver name given, no configuration file either.
Thu Jan 19 14:26:46 2017 [ERROR] The easiest way to get started is to edit the example configuration file
Thu Jan 19 14:26:46 2017 [ERROR] and to append the full path to that file to the dnscrypt-proxy command.
Thu Jan 19 14:26:46 2017 [ERROR] Example: dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
Thu Jan 19 14:26:46 2017 [ERROR] The local list of public resolvers is loaded from: [/usr/local/share/dnscrypt-proxy/dnscrypt-resolvers.csv]
Thu Jan 19 14:26:46 2017 [ERROR] Consult https://dnscrypt.org for more information about dnscrypt-proxy.
dirname: missing operand
Try 'dirname --help' for more information.


The path to resolvers.csv on dnscrypt-loader script
differs from dnscrypt-proxy setup
Please change dnscrypt-loader 'cCSVBaseDir' and 'cSIGBaseDir' parameters to
cCSVBaseDir='/'
cSIGBaseDir='/'


Edit script at /usr/local/sbin/dnscrypt-loader

**Comment by GortCodex** [comment]
Run this command please
dnscrypt-proxy | awk  '/resolvers.csv/ NR>1 {print $1}' RS=[ FS=]

**Comment by jpgpi250** [comment]
result:
Thu Jan 19 15:37:04 2017 [WARNING] This system doesn't provide enough entropy to quickly generate high-quality random numbers
Thu Jan 19 15:37:04 2017 [WARNING] Installing the rng-utils/rng-tools or haveged packages may help.
Thu Jan 19 15:37:04 2017 [WARNING] On virtualized Linux environments, also consider using virtio-rng.
Thu Jan 19 15:37:04 2017 [WARNING] The service will not start until enough entropy has been collected.
Thu Jan 19 15:37:04 2017 [ERROR] Error: no resolver name given, no configuration file either.
Thu Jan 19 15:37:04 2017 [ERROR] The easiest way to get started is to edit the example configuration file
Thu Jan 19 15:37:04 2017 [ERROR] and to append the full path to that file to the dnscrypt-proxy command.
Thu Jan 19 15:37:04 2017 [ERROR] Example: dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
Thu Jan 19 15:37:04 2017 [ERROR] The local list of public resolvers is loaded from: [/usr/local/share/dnscrypt-proxy/dnscrypt-resolvers.csv]
Thu Jan 19 15:37:04 2017 [ERROR] Consult https://dnscrypt.org for more information about dnscrypt-proxy.

**Comment by jpgpi250** [comment]
I noticed there is no longer a dnscrypt-proxy.conf file in /usr/local/etc
I've copied my backup configuration file in that location (from dnscrypt v1.9.1)
rebooted the system, the result (and output) are the same

**Comment by GortCodex** [comment]
Ok, I'll need some time to investigate and fix (ASAP) this incompatibility See the message Frank Denis posted. Upgrading is unnecessary except if you use musl libc. 

![frankupgrade](https://cloud.githubusercontent.com/assets/16090550/22110792/ca8427dc-de3b-11e6-9621-e07f32477faf.gif)

**Comment by jpgpi250** [comment]
just letting you know that v1.9.2 has the same problem. The last known good version is 1.9.1

**Comment by GortCodex** [comment]
Thank, I'll simulate with each version to correct the errors.

**Comment by Quentin-M** [comment]
Same here on Ubuntu.

**Comment by Firestorrrm** [comment]
Any update on this issue?

**Comment by meeeo** [comment]
Me too, the same problem, dnscrypt-loader v1.2 and dnscrypt-proxy v1.9.4 on raspberry pi raspbian jessie.

**Comment by fluential** [comment]
Fix https://github.com/GortCodex/DNSCrypt-Loader/pull/14
