### ISSUE TITLE
Resolvers.csv failed to download

### ISSUE THREAD

**Issue by budbay** [GortCodex/DNSCrypt-Loader#12]
When trying to update resolvers, it fails to download. The download takes an unusually long time to start then gives the error "   awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted"  looking at the resolvers.csv changes it looks like jedisct1 may have changed the format some. I am still on an older version of dnscrypt-proxy so probably unrelated to issues with latest version.

**Comment by GortCodex** [comment]
I myself still use the old version of dnscrypt-proxy until I get time to update the dnscrypt-loader and find no problems updating and using the resolvers. I tried to reproduce your problem but everything worked normally. If the version problem does not apply to you, verify that the resolvers download did not end with errors. A "division by zero" error may occur if the downloaded file reading fails. If you are using a dnscrypt-proxy resolver during the download make sure it is responding without time-out. Finally locate and delete all resolvers.csv files and try again. I'll check if there was any change in the .csv layout, but as I said I did not encounter any problems here. Thank you for reporting the issue.

**Comment by budbay** [comment]
Well apparently it was just some kind of strange issue last night. Tried again today to troubleshoot further and worked no problem.  Sorry for the false report, but I did spend a fair amount of time trying different solutions. Anyway look forward to the update this is a very handy program. Thanks.

**Comment by GortCodex** [comment]
No problem, you're welcome.
