### ISSUE TITLE
I running DNSCrypt Loader 1.2 is fails 

### ISSUE THREAD

**Issue by joehk2017** [GortCodex/DNSCrypt-Loader#15]
Hello , 

I  looked your page how to setup but is fails , what can i do ?
Where can find configuration file ? This mean /usr/local/etc/dnscrypt-proxy.conf or /usr/local/sbin/dnscrypt-loader ?

Thank 

https://ibb.co/iOLeX5
https://ibb.co/d8WmC5

**# dnscrypt-loader** 

root@debian:~# dnscrypt-loader 1.2
Tue Aug  1 09:18:06 2017 [ERROR] Error: no resolver name given, no configuration file either.
Tue Aug  1 09:18:06 2017 [ERROR] The easiest way to get started is to edit the example configuration file
Tue Aug  1 09:18:06 2017 [ERROR] and to append the full path to that file to the dnscrypt-proxy command.
Tue Aug  1 09:18:06 2017 [ERROR] Example: dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
Tue Aug  1 09:18:06 2017 [ERROR] The local list of public resolvers is loaded from: [/usr/local/share/dnscrypt-proxy/dnscrypt-resolvers.csv]
Tue Aug  1 09:18:06 2017 [ERROR] Consult https://dnscrypt.org for more information about dnscrypt-proxy.
dirname: missing operand
Try 'dirname --help' for more information.

The path to resolvers.csv on dnscrypt-loader script 
differs from dnscrypt-proxy setup 
Please change dnscrypt-loader 'cCSVBaseDir' and 'cSIGBaseDir' parameters to
cCSVBaseDir='/' 
cSIGBaseDir='/' 

Edit script at /usr/local/sbin/dnscrypt-loader 

Hope can help me , Thank 

**# DNSCrypt-proxy 1.95**

**Comment by GortCodex** [comment]
Hi, thanks for trying to use the script. The error message you posted was issued by dnscrypt-proxy and not by dnscrypt-loader, this may have confused you. Please check the installation of dnscrypt-proxy. If you would like to use dnscrypt-loader install version 1.6 of dnscrypt-proxy. Take a look here: https://github.com/GortCodex/DNSCrypt-Loader/pull/14

**Comment by joehk2017** [comment]
Hi , 

I think you should statement your version not yet support  dnscrypt-proxy new version . 

(e.g) IF you want to use DNSCrypt Loader please use version 1.6 dnscrypt-proxy.

Because for new user not to know what happen

Thank !

**Comment by GortCodex** [comment]
Hi, you're right. I am updating the manual and putting a warning about using the versions there.
