### ISSUE TITLE
How the hell make this work?

### ISSUE THREAD

**Issue by verdulo** [GortCodex/DNSCrypt-Loader#16]
I'm using Linux Mint, in network manager I can enter only IP addresses without ports, so in file '/usr/local/sbin/dnscrypt-loader' I typed
```
cPrimaryIP="127.0.0.2"
cPrimaryPort="53"
```
The problem is that when I try to run dnscrypt-loader I get error:
```
Port :53 is already in use by another system process.
Please select different port for primary resolver
```
What to do now?

**Comment by jedisct1** [comment]
Step 1: use a more friendly tone to ask for help.
