### ISSUE TITLE
Got 2 errors

### ISSUE THREAD

**Issue by cronner** [GortCodex/DNSCrypt-Loader#17]
root@server:~# dnscrypt-loader -x
 --- Running DNS Leak Test. Please wait ---  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   351  100   351    0     0    772      0 --:--:-- --:--:-- --:--:--   771
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
**curl: (6) Could not resolve host: 066244feed2ef0361d01422c.et.dns-oarc.net**
 DNSCrypt-proxy  Loaded instances

 --- Configs ---  
 Running as     = root
 Anonymous only = true
 Sign check     = false
 IP Version     = ipv4

 --- Primary DNS ---  
 Status         = Running [3706]
 Execution time = 17:10 00:00 (Date days-hh:mm:ss)
 Proxy IP       = 127.0.0.1:5553
 Resolver IP    = 82.103.131.172:443
 Resolver name  = 2.dnscrypt-cert.cryptostorm.is
 Resolver test  = Dig Query Time  : 57 msec

 --- Secondary DNS ---  
 Status         = Running [6551]
 Execution time = 17:10 00:00 (Date days-hh:mm:ss)
 Proxy IP       = 127.0.0.1:5554
 Resolver IP    = 185.60.147.77:443
 Resolver name  = 2.dnscrypt-cert.cryptostorm.is
 Resolver test  = Dig Query Time  : 41 msec

 --- DNS Servers detected during DNS Leak Test ---  
**grep: /tmp/dnscrypt-loader//index.html: No such file or directory**

**Comment by GortCodex** [comment]
Hi, it looks like the DNS query for entropy.dns-oarc.net/test has temporarily failed. This prevented the creation of the file. Please try to exchange your DNS servers
