### ISSUE TITLE
Is the repo still alive?

### ISSUE THREAD

**Issue by maxiride** [GortCodex/DNSCrypt-Loader#18]
The [last release](https://github.com/GortCodex/DNSCrypt-Loader/releases) is from one year ago, is this loader still stable and\or ready to use? Should I use dnscrypt manually without loaders?

**Comment by GortCodex** [comment]
Hi, Absolutely. The project is still alive, but the dnscrypt-proxy code has undergone great changes and I need time to adjust the project. You can use dnscrypt-loader with old versions of dnscrypt-proxy without problems (try version 1.6) See the manual and more details on the Closed Issues tab.

**Comment by maxiride** [comment]
Thank you very much for the insight! :relaxed:

**Comment by maxiride** [comment]
The installation and use went fine =)

Is there an ETA for the updates needed to use the latest version of dnscrypt? Just to have an general idea :wink:
