### ISSUE TITLE
 Sign check = false

### ISSUE THREAD

**Issue by styrenes** [GortCodex/DNSCrypt-Loader#19]
ubuntu 16.04 system.
 
 DNSCrypt-proxy  Loaded instances

 --- Configs ---  
 Running as     = root
 Anonymous only = true
 Sign check     = false
 IP Version     = all

 --- Primary DNS ---  
 Status         = Running [6947]
 Execution time = 20:03 41:52 (Date days-hh:mm:ss)
 Proxy IP       = 127.0.0.1:5553
 Resolver IP    = [2001:1448:243::dc2]:443
 Resolver name  = 2.dnscrypt-cert.resolver2.dnscrypt.eu
 Resolver test  = Dig Query Time  :  msec

 --- Secondary DNS ---  
 Status         = Running [20366]
 Execution time = 19:32 01:12:42 (Date days-hh:mm:ss)
 Proxy IP       = 127.0.0.1:5554
 Resolver IP    = 192.209.63.8
 Resolver name  = 2.dnscrypt-cert.fvz-rec-us-ler-01.dnsrec.meo.ws
 Resolver test  = Dig Query Time  :  msec

**Comment by styrenes** [comment]
How can I fix it. Do you speak Chinese?

**Comment by GortCodex** [comment]
Sorry, I do not speak Chinese. To enable/disable resolvers.cvs signature verification, follow the settings below, thank you.
https://github.com/jedisct1/minisign

Resolvers.csv signature check using Minisign
By default, this setting is disabled to allow you to install and configure Minisign.
Please refer to https://github.com/jedisct1/minisign
After that, you can set cEnableSignCheck=true and the integrity check will run properly

cEnableSignCheck=false

true = perform resolvers.csv minisgn verification. minisgn application must be installed
false = ignore minisgn verification

cEnableSignCheck=true

**Comment by styrenes** [comment]
Thanks
Here is the problem.

user@user-ThinkPad-xxx:~/Downloads/minisign-0.7/build$ cmake ..
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIB_SODIUM
    linked by target "minisign" in directory /home/user/Downloads/minisign-0.7

-- Configuring incomplete, errors occurred!
See also "/home/user/Downloads/minisign-0.7/build/CMakeFiles/CMakeOutput.log".

**Comment by styrenes** [comment]
After I have installed libsodium-dev, It is ok now.

**Comment by styrenes** [comment]
In ubuntu system, there is no "/usr/local/share" directory

sudo dnscrypt-loader -x

 --- Running DNS Leak Test. Please wait ---  
/usr/local/sbin/dnscrypt-loader: line 1395: curl: command not found
 DNSCrypt-proxy  Loaded instances

 --- Configs ---  
 Running as     = root
 Anonymous only = true
 Sign check     = true
 IP Version     = all

 --- Primary DNS ---  
 Status         = Running [4082]
 Execution time = 10:13 02:29 (Date days-hh:mm:ss)
 Proxy IP       = 127.0.0.1:5553
 Resolver IP    = [2001:1448:243::dc2]:443
 Resolver name  = 2.dnscrypt-cert.resolver2.dnscrypt.eu
 Resolver test  = Dig Query Time  :  msec

 --- Secondary DNS ---  
 Status         = Running [4357]
 Execution time = 10:14 01:34 (Date days-hh:mm:ss)
 Proxy IP       = 127.0.0.1:5554
 Resolver IP    = 192.209.63.8
 Resolver name  = 2.dnscrypt-cert.fvz-rec-us-ler-01.dnsrec.meo.ws
 Resolver test  = Dig Query Time  :  msec


 --- DNS Servers detected during DNS Leak Test ---  
grep: /tmp/dnscrypt-loader//index.html: No such file or directory

**Comment by styrenes** [comment]
Is that OK now?

sudo dnscrypt-loader -x
 --- Running DNS Leak Test. Please wait ---  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   351  100   351    0     0    318      0  0:00:01  0:00:01 --:--:--   318
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  7941    0  7941    0     0    703      0 --:--:--  0:00:11 --:--:--  1863
 DNSCrypt-proxy  Loaded instances

 --- Configs ---  
 Running as     = root
 Anonymous only = true
 Sign check     = true
 IP Version     = all

 --- Primary DNS ---  
 Status         = Running [4082]
 Execution time = 10:13 11:09 (Date days-hh:mm:ss)
 Proxy IP       = 127.0.0.1:5553
 Resolver IP    = [2001:1448:243::dc2]:443
 Resolver name  = 2.dnscrypt-cert.resolver2.dnscrypt.eu
 Resolver test  = Dig Query Time  :  msec

 --- Secondary DNS ---  
 Status         = Running [4357]
 Execution time = 10:14 10:14 (Date days-hh:mm:ss)
 Proxy IP       = 127.0.0.1:5554
 Resolver IP    = 192.209.63.8
 Resolver name  = 2.dnscrypt-cert.fvz-rec-us-ler-01.dnsrec.meo.ws
 Resolver test  = Dig Query Time  :  msec


 --- DNS Servers detected during DNS Leak Test ---  
 Your DNS Server:  221.228.15.78     
 Your DNS Server:  180.108.0.18      
 Your DNS Server:  221.228.15.94

**Comment by GortCodex** [comment]
It seems all okay now, you've solved all the problems. Thanks for using dnscrypt-loader!

**Comment by styrenes** [comment]
dig @127.0.0.1 -p 5553 www.youtube.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.0.1 -p 5553 www.youtube.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by styrenes** [comment]
user@user-Th:~$ sudo dnscrypt-loader -x
 --- Running DNS Leak Test. Please wait ---  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   351  100   351    0     0    582      0 --:--:-- --:--:-- --:--:--   582
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 12590    0 12590    0     0   1002      0 --:--:--  0:00:12 --:--:--  3132
 DNSCrypt-proxy  Loaded instances

 --- Configs ---  
 Running as     = root
 Anonymous only = true
 Sign check     = true
 IP Version     = all

 --- Primary DNS ---  
 Status         = Running [14246]
 Execution time = 14:33 00:26 (Date days-hh:mm:ss)
 Proxy IP       = 127.0.0.1:5553
 Resolver IP    = 185.94.193.234:443
 Resolver name  = 2.dnscrypt-cert.cryptostorm.is
 Resolver test  = Dig Query Time  : 513 msec

 --- Secondary DNS ---  
 Status         = Running [10846]
 Execution time = 14:29 04:42 (Date days-hh:mm:ss)
 Proxy IP       = 127.0.0.1:5554
 Resolver IP    = 167.114.84.132:443
 Resolver name  = 2.dnscrypt-cert.cryptostorm.is
 Resolver test  = Dig Query Time  : 392 msec


 --- DNS Servers detected during DNS Leak Test ---  
 Your DNS Server:  221.228.15.78     
 Your DNS Server:  221.g1df6    
 Your DNS Server:  180.10dfg8      
 Your DNS Server:  221.2dgf6     
 Your DNS Server:  221.2dgfret     
user@user-:~$ dig @127.0.0.1 -p 5553 www.youtube.com +time=30

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.0.1 -p 5553 www.youtube.com +time=30
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11979
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.youtube.com.		IN	A

;; ANSWER SECTION:
www.youtube.com.	46384	IN	CNAME	youtube-ui.l.google.com.
youtube-ui.l.google.com. 270	IN	A	216.58.205.174

;; Query time: 547 msec
;; SERVER: 127.0.0.1#5553(127.0.0.1)
;; WHEN: Sun Oct 22 14:34:53 CST 2017
;; MSG SIZE  rcvd: 83

**Comment by GortCodex** [comment]
Are you receiving timeout when doing a DNS query? (connection timed out; no servers could be reached) Is this the problem? As you know, this depends on the availability and traffic of the selected server. 513 msec is a high value. 

Personally I use "dnscrypt-loader -r" and "dnscrypt-loader -s" until I find the best response time for a server. At some point the chosen server will be unavailable or slow and then you will need to switch to another server. Have you tried to do that? You can automate this by using cron. Did I understand your question correctly?


The same query made here:

 dig @127.0.0.1 -p 5553 www.youtube.com

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7 <<>> @127.0.0.1 -p 5553 www.youtube.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64547
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.youtube.com.               IN      A

;; ANSWER SECTION:
www.youtube.com.        1592    IN      CNAME   youtube-ui.l.google.com.
youtube-ui.l.google.com. 136    IN      A       216.58.201.238

;; Query time: 340 msec
;; SERVER: 127.0.0.1#5553(127.0.0.1)
;; WHEN: Sun Oct 22 14:31:04 -02 2017
;; MSG SIZE  rcvd: 94
