### ISSUE TITLE
cProxyBaseDir, cCSVBaseDir, cSIGBaseDir - no resolver name given,

### ISSUE THREAD

**Issue by blub4747** [GortCodex/DNSCrypt-Loader#21]
HI guys,

I installed DNSCrypt-Loader on my debian/armbian system with dnscrypt-proxy/stable,now 1.9.4-1 armhf [installed] on it.

When I try to run DNSCrypt-Loader I got the first error msg

> touch: cannot touch '/usr/local/share/dnscrypt-proxy//dcploader-resolvers.csv': No such file or directory

>The path to dnscryp-proxy on dnscrypt-loader script 
>differs from dnscrypt-proxy setup 
>Please change dnscrypt-loader 'cProxyBaseDir' parameter to 
>cProxyBaseDir='/usr/sbin/'

>Edit script at /usr/local/sbin/dnscrypt-loader 

Once I preformed the following change
#cProxyBaseDir="/usr/local/sbin/" ->
cProxyBaseDir="/usr/sbin/"

I now get the different error msg

> touch: cannot touch '/usr/local/share/dnscrypt-proxy//dcploader-resolvers.csv': No such file or directory
> Tue Jan  2 11:04:58 2018 [ERROR] Error: no resolver name given, no configuration file either.
> Tue Jan  2 11:04:58 2018 [ERROR] The easiest way to get started is to edit the example configuration > file
> Tue Jan  2 11:04:58 2018 [ERROR] and to append the full path to that file to the dnscrypt-proxy command.
Tue Jan  2 11:04:58 2018 [ERROR] Example: dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
Tue Jan  2 11:04:58 2018 [ERROR] The local list of public resolvers is loaded from: [/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv]
Tue Jan  2 11:04:58 2018 [ERROR] Consult https://dnscrypt.org for more information about dnscrypt-proxy.
dirname: missing operand
Try 'dirname --help' for more information.

> The path to resolvers.csv on dnscrypt-loader script 
differs from dnscrypt-proxy setup 
Please change dnscrypt-loader 'cCSVBaseDir' and 'cSIGBaseDir' parameters to
cCSVBaseDir='/' 
cSIGBaseDir='/' 

> Edit script at /usr/local/sbin/dnscrypt-loader 
Can someone please tell me which section I need to modify so dnscrypt-loader can download the the resolvers file.

Thx, blub4747

**Comment by GortCodex** [comment]
Hello, unfortunately dnscrypt-loader still does not support the version of dnscryp-proxy that you have installed. Try using previous versions.

**Comment by blub4747** [comment]
thank you for that information.
Which version will than corporate with Debian based systems?

**Comment by GortCodex** [comment]
I keep using the dnscrypt-proxy 1.6.0 version with no side effects. You can also use versions immediately below 1.9. Good luck.
