### ISSUE TITLE
installing on Linux Mint

### ISSUE THREAD

**Issue by verdulo** [GortCodex/DNSCrypt-Loader#22]
How to install this on Linux Mint?

In network settings I can type only IP-adresses - not ports - so I have to use port 53, I changed in the file "dnscrypt-loader":
cPrimaryIP="127.0.0.2"
cPrimaryPort="53"

After installing and running I've got the error:
"Port :53 is already in use by another system process.
Please select different port for primary resolver"

What to do now?

**Comment by GortCodex** [comment]
Hello, As you have seen there is already a DNS service running on port 53 and it is not possible to run dnscrypt-proxy on the same port. In order for dnscrypt-proxy to use port 53 you should either disable the current service or use an alternate port for dnscrypt-proxy and in your network settings set the primary DNS server to 127.0.0.2:5053 for example. However, if it was dnscrypt-loader who used this port, try using "dnscrypt-loader -k" on the terminal to kill the service. Also try "dnscrypt-loader -s" to see the ip: port that was used by dnscrypt-proxy.
