### ISSUE TITLE
how do I get dnscrypt or dnscrypt loader to work 

### ISSUE THREAD

**Issue by Leon8200** [GortCodex/DNSCrypt-Loader#4]
![screenshot - 12192015 - 02 28 22 am](https://cloud.githubusercontent.com/assets/16346096/11912054/dab55368-a5f9-11e5-9c24-8989d45ab874.png)

**Comment by GortCodex** [comment]
Olá, Parece que a página do DNSCrypt-proxy não pode ser encontrada naquele momento. Por favor, reveja suas configurações de DNS e tente novamente. Esse erro ocorre numa falha temporária de seu servidor DNS atual.
Configure o DNSCrypt-loader após acessar corretamente o link usando seu browser https://download.dnscrypt.org/dnscrypt-proxy . Thanks

**Comment by GortCodex** [comment]
Hello, It seems that DNSCrypt-proxy page can not be found at that time. Please review your DNS settings and try again. This error occurs in a temporary failure of your current DNS server.
Set the DNSCrypt-loader after properly access the link using your browser https://download.dnscrypt.org/dnscrypt-proxy . Thanks

**Comment by Leon8200** [comment]
thanks for the reply, I can go to the link in my browser but the dnscrypt loader cant, I downloaded the update, where am I supposed to put it?

**Comment by GortCodex** [comment]
The resolver.csv file should be placed in  /usr/local/share/dnscrypt-proxy/  folder. Thanks.

**Comment by Leon8200** [comment]
ok, I placed it in the directory, but dnscrypt loader still wont give me a list of resolvers to connect to, and if I try to update it, it wont connect!?!?!

**Comment by GortCodex** [comment]
Hello Leon,
I'm sorry you continue with problems. Let's try some other alternatives:

The Curl is receiving an error that does not know how to interpret and stops the download.
( note that there is a persistent error in your internet browsing but let's ignore it)

So, please make a copy of /usr/local/sbin/dnscrypt-loader for safety e
edit the file

sudo vi /usr/local/sbin/dnscrypt-loader

Change the line 953:

if [$ {httpStatus} == "301"] || [$ {HttpStatus} == "404"] || [$ {HttpStatus} == "?" ]; Then

TO:

if [$ {httpStatus} == "301"] || [$ {HttpStatus} == "404"]; Then

Save the file and run the script

sudo dnscrypt-loader 

You can check the log to debug the procedures errors  

If you continue in troubles let me know and we try some other procedures

Thanks

**Comment by Leon8200** [comment]
it still wont work

**Comment by GortCodex** [comment]
Well, it really does not seem to be a problem specific to DNSCrypt-proxy. Please review settings as SELinux enabled, sudo rights, and if possible, install the script on another computer as root for testing. Thanks,
