### ISSUE TITLE
DNScrypt-Loader not running at startup

### ISSUE THREAD

**Issue by ghost** [GortCodex/DNSCrypt-Loader#7]
Running Fedora 24:
Installed DNScrypt-proxy from fedora package
Installed DNScrypt-Loader as instructed on the github page. Edited /usr/local/sbin/dnscrypt-loader successfully.  Used the GUI to download new resolver, set IP filter to all, set privacy filter, and set primary and secondary servers successfully.  Verified service is running. Rebooted. Upon startup, ran:

systemctl status dcp-loader, says:
Jun 26 22:51:51 localhost.localdomain systemd[1]: Starting SYSV: DNSCrypt-proxy daemon Loader...
Jun 26 22:51:51 localhost.localdomain systemd[1]: Started SYSV: DNSCrypt-proxy daemon Loader.
Jun 26 22:51:51 localhost.localdomain dcp-loader[6015]: [  OK  ]
Jun 26 22:51:51 localhost.localdomain dnscrypt-loader[6087]: differs from dnscrypt-proxy setup
Jun 26 22:51:51 localhost.localdomain dnscrypt-loader[6093]: cProxyBaseDir='/sbin/'

Also ran:
[root@localhost lee]# service dcp-loader status           [  OK  ]
Warning: /usr/sbin/dnscrypt-proxy is not running.
Please select a new resolver to start
[root@localhost lee]#                                     [  OK  ]

I verified the path for cProxyBaseDir in /usr/local/sbin/dnscrypt-loader, is set to "/usr/sbin/"
Help

**Comment by GortCodex** [comment]
Thanks for using DNSCrypt-Loader rowyourboat.
Some things you can try:

Check if SELinux is disabled on Fedora 24 and then run the installer again using:
  Option 3 - Disable DNSCrypt-loader at boot time
  Option 2 - Enable DNSCrypt-loader at boot time

If this does not work, try installing the service manually:

at the command prompt open the folder where it was downloaded DNSCrypt-Loader
and run these commands as root:

  cp dcp-loader-redhat /etc/init.d/dcp-loader
  chmod +x  /etc/init.d/dcp-loader
  chkconfig --add dcp-loader
  dcp-loader chkconfig --level 2345 on

Alternatively you can use systemctl to enable services in Fedora 24 described here

https://docs.fedoraproject.org/en-US/Fedora/24/html/System_Administrators_Guide/ch-Services_and_Daemons.html#s3-services-configuration-enabling
