### ISSUE TITLE
Opensuse support

### ISSUE THREAD

**Issue by ArjonBu** [GortCodex/DNSCrypt-Loader#8]
Hello, 
Can you please add opensuse support? I think your script is great. 
Thank you.

**Comment by GortCodex** [comment]
Hello, a version for OpenSUSE will be available soon. Thanks for using DNSCrypt-Loader.

**Comment by ArjonBu** [comment]
You might want to use opensuse build service https://en.opensuse.org/Portal:Build_Service

**Comment by GortCodex** [comment]
Cool, thanks for the tip. I'll create a package for openSUSE soon

**Comment by ArjonBu** [comment]
Thanks! Would you mind replying to this thread when you do? It would be great!

**Comment by GortCodex** [comment]
No problem I will notify!

**Comment by ArjonBu** [comment]
BTW Opensuse build service creates packages and repos for all distros. It could make your work easier.

**Comment by GortCodex** [comment]
Hello, rpm packages are available for download. Take a look at the installation guide . Thanks for the tip.

**Comment by ArjonBu** [comment]
Thank you!
